---
title: "Request functions in massdatabase"
author:
- name: Xiaotao Shen (https://www.shenxt.info/)
date: "Created on 2022-05-11 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{request_functions}
  %\VignettePackage{massdatabase}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = TRUE,
  out.width = "100%"
)
```

"Request functions" is 

# **Request**

Get the information of all compounds in KEGG (https://www.genome.jp/kegg/compound/).

```{r,eval=TRUE,warning=FALSE, R.options="", message=TRUE, cache=TRUE}
library(massdatabase)
compound_info <- 
  request_kegg_compound_info()
head(compound_info)
```

Get the information of all drugs in KEGG (https://www.genome.jp/kegg/drug/).

```{r,eval=TRUE, warning=FALSE, R.options="", message=TRUE, cache=TRUE}
drug_info <- 
  request_kegg_drug_info()
head(drug_info)
```

Get one metabolite information.

```{r,eval=TRUE, warning=FALSE, R.options="", message=TRUE, cache=TRUE}
x <-
  request_kegg_compound(compound_id = "C02886", return_form = "list")
x
```

```{r,eval=TRUE, warning=FALSE, R.options="", message=TRUE, cache=TRUE}
y <-
  request_kegg_compound(compound_id = "C02886", return_form = "data.frame")
y
```

Get one drug information.

```{r,eval=TRUE, warning=FALSE, R.options="", message=TRUE, cache=TRUE}
x <-
  request_kegg_drug(drug_id = "D00001", return_form = "list")
x
```

```{r,eval=TRUE, warning=FALSE, R.options="", message=TRUE, cache=TRUE}
y <-
  request_kegg_drug(drug_id = "D00001", return_form = "data.frame")
y
```


# **Session information**

```{r,eval=TRUE,warning=FALSE, R.options="", message=FALSE, cache=TRUE}
sessionInfo()
```


