globalVariables(names = c(".", "database",
                          "score1",
                          "score2",
                          "Lab.ID",
                          "query",
                          "Compound.name",
                          "Synonyms",
                          "ACCESSION_NUMBER",
                          "BIOOGICAL",
                          "ACTIVITY",
                          "CAS.ID",
                          "CHEBI_ID",
                          "CHEMICAL_DATA",
                          "COMMON NAME",
                          "COMPOUND_ID",
                          "Compound.name",
                          "DATA No",
                          "DRUGBANK.ID",
                          "FOODB.ID",
                          "FORMULA",
                          "Formula",
                          "HMDB.ID",
                          "ID",
                          "INFORMANT",
                          "Image",
                          "KEGG.ID",
                          "KEGG_DRUG.ID",
                          "KEGG_GLYCAN.ID",
                          "LANGUAGE",
                          "LIPIDMAPS.ID",
                          "Lab.ID",
                          "Lipid class",
                          "METACYC.ID",
                          "MOL.WT(average)",
                          "NAME",
                          "PUBCHEM.ID",
                          "RT",
                          "SOURCE",
                          "SPECIES",
                          "SPECIES_ACCESSION",
                          "SYMBOL",
                          "Submitter",
                          "Synonyms",
                          "TYPE",
                          "WIKIPEDIA.ID",
                          "download.file",
                          "match_table",
                          "mz",
                          "mz.neg",
                          "mz.pos",
                          "name",
                          "query",
                          "value",
                          "BIOOGICAL ACTIVITY"))
